name: exchange-rate
author: CHAI YO MIN
description: Update a pinned gist to contain the latest exchange rate of a user
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'clipboard'
  color: 'blue'
